#!/bin/bash

case $newlang in
en_US)
  a_enter=' ⇢  Press enter to continue'
  a_back=' ⇢  RETURN'
  a_selection_fun=' ⇢  Select an option:'
  ;;
esac

# variables
export _hora=$(printf '%(%H:%M:%S)T')
export _fecha=$(printf '%(%D)T')

export numero='^[0-9]+$'
export texto='^[A-Za-z]+$'
export txt_num='^[A-Za-z0-9]+$'

# 🔹color interfaces🔹colored interfaces
msg() {
   COLOR[0]='\033[1;37m'  # WHITE
   COLOR[1]='\e[31m'      # RED
   COLOR[2]='\e[32m'      # GREEN
   COLOR[3]='\e[33m'      # YELLOW
   COLOR[4]='\e[34m'      # BLUE
   COLOR[5]='\e[91m'      # MAGENTA
   COLOR[6]='\033[1;97m'  # BRIGHT WHITE (used as teal in original?)
   COLOR[7]='\e[36m'      # TEAL
   COLOR[8]='\e[30m'      # BLACK
   COLOR[9]='\033[34m'    # BLUE
   
  NEGRITO='\e[1m'
  SEMCOR='\e[0m'

  case $1 in
  -ne) cor="${COLOR[1]}${NEGRITO}" && echo -ne "${cor}${2}${SEMCOR}" ;;
  -nazu) cor="${COLOR[6]}${NEGRITO}" && echo -ne "${cor}${2}${SEMCOR}" ;;
  -nverd) cor="${COLOR[2]}${NEGRITO}" && echo -ne "${cor}${2}${SEMCOR}" ;;
  -nama) cor="${COLOR[3]}${NEGRITO}" && echo -ne "${cor}${2}${SEMCOR}" ;;
  -ama) cor="${COLOR[3]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -verm) cor="${COLOR[3]}${NEGRITO}[!] ${COLOR[1]}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -verm2) cor="${COLOR[1]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -verm3) cor="${COLOR[1]}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -teal) cor="${COLOR[7]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -teal2) cor="${COLOR[7]}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -blak) cor="${COLOR[8]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -blak2) cor="${COLOR[8]}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -azu) cor="${COLOR[6]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -blu) cor="${COLOR[9]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -blu1) cor="${COLOR[9]}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -verd) cor="${COLOR[2]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -bra) cor="${COLOR[0]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
  -bar) cor="${COLOR[1]}┌──────────────────────────────────────────────┐" && echo -e "${cor}${SEMCOR}" ;;
  -bar0) cor="${COLOR[1]}└──────────────────────────────────────────────┘" && echo -e "${cor}${SEMCOR}" ;;
  -bar2) cor="${COLOR[7]}===============================================" && echo -e "${cor}${SEMCOR}" ;;
  -bar3) cor="${COLOR[1]} ──────────────────────────────────────────────" && echo -e "${cor}${SEMCOR}" ;;
  -bar4) cor="${COLOR[7]}-----------------------------------------------" && echo -e "${cor}${SEMCOR}" ;;
  esac
}

# 🔹text centering
print_center() {
  if [[ -z $2 ]]; then
    text="$1"
  else
    col="$1"
    text="$2"
  fi

  while read -r line; do
    unset space
    x=$(((45 - ${#line}) / 2))
    space=""
    for ((i = 0; i < x; i++)); do
      space+=' '
    done
    space+="$line"
    if [[ -z $2 ]]; then
      msg -azu "$space"
    else
      msg "$col" "$space"
    fi
  done <<< "$(echo -e "$text")"
}

print_title() {
  if [[ -z $2 ]]; then
    text="$1"
  else
    col="$1"
    text="$2"
  fi

  while read -r line; do
    unset space
    x=$(((53 - ${#line}) / 2))
    space=""
    for ((i = 0; i < x; i++)); do
      space+=' '
    done
    space+="$line"
    if [[ -z $2 ]]; then
      msg -azu "$space"
    else
      msg "$col" "$space"
    fi
  done <<< "$(echo -e "$text")"
}

sub_title() {
  if [[ -z $2 ]]; then
    text="$1"
  else
    col="$1"
    text="$2"
  fi

  while read -r line; do
    unset space
    x=$(((54 - ${#line}) / 2))
    space=""
    for ((i = 0; i < x; i++)); do
      space+=' '
    done
    space+="$line"
    if [[ -z $2 ]]; then
      msg -azu "$space"
    else
      msg "$col" "$space"
    fi
  done <<< "$(echo -e "$text")"
}

# 🔹titles and headings
title() {
  clear
  msg -bar
  if [[ -z $2 ]]; then
    print_center -blu1 "$1"
  else
    print_center "$1" "$2"
  fi
  msg -bar0
}

main_title() {
  clear
  msg -bar
  if [[ -z $2 ]]; then
    print_title -blu1 "$1"
  else
    print_title "$1" "$2"
  fi
  msg -bar0
}

title_sub() {
  clear
  msg -bar
  if [[ -z $2 ]]; then
    sub_title -blu1 "$1"
  else
    sub_title "$1" "$2"
  fi
  msg -bar0
}

# completion of tasks🔹home
enter() {
  msg -bar
  text="►► ${a_enter:-Press enter to continue} ◄◄"
  if [[ -z $1 ]]; then
    print_center -ama "$text"
  else
    print_center "$1" "$text"
  fi
  read -r
}

# option, return back/back🔹option, go back go back
back() {
  msg -bar
  echo -ne "$(msg -verd " [0]") $(msg -verm2 ">") "
  msg -bra "\033[1;41m${a_back:-GO BACK}"
  msg -bar0
}

exit2home() {
  msg -bar
  echo -ne "$(msg -verd " [0]") $(msg -verm2 ">") "
  msg -bra "\033[1;41m${a_back:-EXIT}"
  msg -bar0
}

inst() {
  print_center -verm2 "${a9:-❗ Please goto Github and reinstall the tool}"
  print_center -verm2 "${a9:-❗ Please goto Github and reinstall the tool}"
  print_center -verm2 "${a9:-❗ Please goto Github and reinstall the tool}"
}

# menu maker (options 1, 2, 3,...)
menu_func() {
  local options=$#
  local array

  for ((num = 1; num <= options; num++)); do
    echo -ne "$(msg -verd " [$num]") $(msg -verm2 ">") "
    # Get the nth argument as an array
    array=(${!num})
    case ${array[0]} in
      -vd) echo -e "\033[1;33m[!]\033[1;32m ${array[@]:1}" ;;
      -vm) echo -e "\033[1;33m[!]\033[1;31m ${array[@]:1}" ;;
      -fi) echo -e "${array[@]:2} ${array[1]}" ;;
      -bar|-bar2|-bar3|-bar4) echo -e "\033[1;37m${array[@]:1}\n$(msg ${array[0]})" ;;
      *) echo -e "\033[1;37m${array[@]}" ;;
    esac
  done
}

# 🔹Numerical selection option
selection_fun() {
  local max_option=$1
  local col
  local selection

  if [[ -z $2 ]]; then
    col="-nazu"
  else
    col="$1"
    max_option="$2"
  fi

  # Validate max_option is a number and <= 13
  if ! [[ $max_option =~ ^[0-9]+$ ]] || (( max_option > 13 )); then
    echo " ⇢ Option is too large or invalid. Please enter a smaller number."
    return 1
  fi

  while true; do
    a_selection_fun=" ⇢  Enter your selection: "
    msg "$col" "$a_selection_fun " >&2
    read -r selection

    if [[ $selection =~ ^[0-9]+$ ]] && (( selection >= 0 && selection <= max_option )); then
      break
    fi

    echo "Invalid input, please enter a number between 0 and $max_option." >&2
    tput cuu1 >&2 && tput dl1 >&2
  done

  echo "$selection"
}

in_option() {
  local option
  if [[ -z $2 ]]; then
    msg -nazu " $1: " >&2
  else
    msg "$1" " $2: " >&2
  fi
  read -r option
  echo "$option"
}

in_option_down() {
  local dat="$1"
  local length=${#dat}
  local cal=$((22 - length / 2))
  local line=''
  for ((i = 0; i < cal; i++)); do
    line+='╼'
  done
  echo -e " $(msg -verm3 "╭$line╼[")$(msg -azu "$dat")$(msg -verm3 "]")"
  echo -ne " $(msg -verm3 "╰╼")\033[37;1m> " && read -r option
}

del() {
  local lines_to_delete=$1
  for ((i = 0; i < lines_to_delete; i++)); do
    tput cuu1 && tput dl1
  done
}

# Since exporting functions is not portable, commenting out exporting functions for safer usage
# export -f msg
# export -f selection_fun
# export -f menu_func
# export -f print_center
# export -f title
# export -f back
# export -f inst
# export -f enter
# export -f in_option
# export -f in_option_down
# export -f del
# export -f exit2home
